### ISSUE TITLE
Sampled systematically overestimating variance

### ISSUE THREAD

**Issue by juhuntenburg** [murraylab/brainsmash#11]
Hi, 

thanks so much for this great tool, it's really filling a gap!

I am creating surrogate maps for different dense brain maps using the Sampled class and in almost all cases I was able to make it work very well by expanding deltas to [0.1 ... 0.9], increasing ns to 1000 and knn to 5000. However in a few cases, the variance seems to always be just a bit higher for the surrogate maps than the empirical map (see below) and I cannot seem to find a way to fix that. 

Do you have any advice?

![image](https://user-images.githubusercontent.com/6514016/86338067-cad7db80-bc49-11ea-9d9d-580b6fc52c37.png)

**Comment by jbburt** [comment]
Hi Julia,

I have noticed the same phenomenon occurring for some brain maps, but I haven't yet found a satisfying remedy for it. Have you looked at the distribution of values in your target brain map? The brain maps that I've analyzed which exhibit systematic overestimation like this have distributions of values that look highly skewed and nothing like a normal distribution. Transforming the brain map values to be normally distributed prior to generating surrogate maps does not solve the problem either, as far as I can tell. This leads me to suspect that this happens when brain maps strongly violate the model's other assumption, stationarity. 

One thing you might also try (if you haven't already) is varying the parameter `pv`, which the model may be sensitive to. If you increase `pv`, does the variogram continue rising/flatten or does it dip back down? The latter could indicate that there are multiple characteristic spatial scales of variation in the map.

**Comment by juhuntenburg** [comment]
Hi Joshua, thanks so much for your reply! I managed to get good enough fits for all maps eventually by tweaking the parameters, so it worked for me. In fact a slightly lower knn value than what I had tried before (3000 in my case) worked better in some maps. But your explanations are helpful, next time I use it I have a better understanding what to watch out for.
