### ISSUE TITLE
Memory issues with volumetric surrogate maps

### ISSUE THREAD

**Issue by ayanmandal120** [murraylab/brainsmash#18]
Hi team,

This is a really great tool that I've found very easy to use so far -- congratulations on an excellent product! I am running into an issue when trying to create volumetric surrogate maps with a file that has ~90,000 values. I followed the instructions/code listed here (https://brainsmash.readthedocs.io/en/latest/example.html#volume-example) but my computer comes close to crashing when I try this. When I stop the program, I find the distmat and index npy files have been created and are taking up about 40GB each, which is well over the amount of storage I have on my local computer. I was wondering if this is what I should expect and I should just do this on a cluster, or if there's something I can alter such that these files don't get so large.

Thanks,
Ayan

**Comment by jbburt** [comment]
Hi Ayan, 

Thanks for the kind words! This file size is not unexpected and the code should take quite some time to run, though I'm not sure exactly how long (less than one day for sure though). I would therefore strongly suggest running this on a cluster if you have access to one. Currently, the only way to circumvent this issue is to use a brain map with fewer values (e.g., by parcellating your data). The disk space requirements scale like N^2, where N is the number of values (~90,000 in this case). 

Josh

**Comment by ayanmandal120** [comment]
Hi Josh,

Thanks for the quick reply! I figured that was probably the case so I have this running on our cluster currently. Happy holidays!

Best,
Ayan

**Comment by jbburt** [comment]
Happy holidays to you as well! Please open a new issue or contact me directly if you run into any more problems.
