### ISSUE TITLE
Cortical Voxelwise negative values surrogate

### ISSUE THREAD

**Issue by slieped** [murraylab/brainsmash#27]
Hi!

I have been using brainSmash for a while, mainly with cortical (surface) data.
For a specific analyses, we do have a volume-based PET info in the cortex. Thus, I thought it would be interesting to also generate surrogate maps with your tool.

The problem I am facing, after following the voxelwise tutorial, is that the surrogate maps show-up with negative values (even though the original map is all positive). Of course, when computing the distance matrix, and parsing the volume data, I only used non-zero cortical voxels.
I have been playing around with the variogram parameters, reducing the percentile distance (to make it more local) and also the number of nearest neighbors. 

For my specific case, this is not a problem, since I will work with correlation afterwards, and the offset is irrelevant, but I was wondering ig this behavior is normal? How should I debug if I am doing something wrong?
Thank you in advance!

V

**Comment by jbburt** [comment]
Hi Victor, 

Are you resampling values from your original map? By default, `resample=False` for both the Base and Sampled classes. When surrogate maps' values are not resampled from the empirical map, the surrogate maps are mean-subtracted prior to returning (for the Sampled class, [here](https://github.com/murraylab/brainsmash/blob/2087867d2e64cb41b61060e01f6de42675c42229/brainsmash/mapgen/sampled.py#L198)). (Note: the mean is subtracted because the variogram is invariant to mean shifts.) You should therefore always have negative values in your surrogate maps (unless the map is identically zero).

If you _are_ resampling, then something is probably wrong... the first thing I would check is whether or not your surrogate maps have the expected distribution of values (ie, equivalent to your original map). 

Josh

**Comment by slieped** [comment]
Ok, you saved my day. Indeed, I needed to resample= True also for Sampled class... I was using it for Base, and did completely miss it here.
Well, apologies for the noobie error.

Thank you for you quick response and for being so instructive in your answer!
have a good one, Josh

**Comment by jbburt** [comment]
No problem -- I'm glad to hear that it was an easy fix!
