### ISSUE TITLE
Use which brain map to generate surrogate data?

### ISSUE THREAD

**Issue by younghoo** [murraylab/brainsmash#31]
Dear expert,

I would like to conduct a spatial correlation between two brain maps and I wonder which map I should use to generate surrogate data. For instance, in the BrainSMASH document, the myelin map is correlated with the thickness map and the myelin map (instead of the thickness map) is used for creating surrogate data. Are there any considerations in the choice?

Sorry that I know this problem is not specific to BrainSMASH, but I would like to know your suggestions.

Thanks!

**Comment by jbburt** [comment]
Hi, thanks for the question! I'm not sure if I have a definitive answer for you, but two thoughts come to mind:

1. Consider your specific analysis; what's the null hypothesis you're testing? In our work, the myelin map was of particular interest, and we compared its spatial topography to a variety of other structural, functional, and transcriptomic brain maps (among them, the cortical thickness map). So in our analyses, the myelin map was of particular interest; thus, we wanted to test the null hypothesis that our statistical findings could be attributed simply to spatial autocorrelation structure in the myelin map, rather than to its unique topography.

2. If you really aren't sure which map to use and your analysis is relatively straightforward (eg, a correlation between two brain maps), you could either:
- generate $N$ surrogate maps for each brain map in your analysis, then build your null distribution from $N^2$ pairwise comparisons, or 
- assuming you're comparing map A to map B, perform two non-parametric tests, first by constructing the null distribution  between map A and surrogate maps derived from map B, then again by comparing map B to surrogate maps derived from map A, and then just report the more conservative of the two (ie, whichever is least significant).

I hope this helps!
Josh

**Comment by younghoo** [comment]
Thank you for the helpful comments. In my case, I want to test the association between case-control effect size map and AHBA gene expression maps. As there is only one effect size map and thousands of genes, I think it is reasonable to permutate the  effect size map to save a lot of computations.
